export const API_ENDPOINTS = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyResetToken: "/auth/verify-reset-token",
  },
  backoffice: {
    dashboard: "/backoffice/dashboard",
    analytics: "/backoffice/analytics",
    analyticsFilters: "/backoffice/analytics/filters",
    users: "/backoffice/users",
    usersSummary: "/backoffice/users/summary",
    userById: (userId: string) => `/backoffice/users/${userId}`,
    verifyUser: (userId: string) => `/backoffice/users/${userId}/verify`,
    activateUser: (userId: string) => `/backoffice/users/${userId}/activate`,
    deactivateUser: (userId: string) => `/backoffice/users/${userId}/deactivate`,
    changeUserRole: (userId: string) => `/backoffice/users/${userId}/role`,
    lockUser: (userId: string) => `/backoffice/users/${userId}/lock`,
    unlockUser: (userId: string) => `/backoffice/users/${userId}/unlock`,
    rejectUser: (userId: string) => `/backoffice/users/${userId}/approve`,
    deleteUser: (userId: string) => `/backoffice/users/${userId}`,
    onboardUser: "/backoffice/users/onboard",
    statusUpdate: (userId: string) => `/backoffice/users/${userId}/status`,
    admins: "/backoffice/admins",
    groups: "/backoffice/groups",
    groupsPending: "/backoffice/groups/pending",
    groupById: (groupId: string) => `/backoffice/groups/${groupId}`,
    groupMembers: (groupId: string) => `/backoffice/groups/${groupId}/members`,
    groupReports: "/backoffice/groups/reports",
    lockGroup: (groupId: string) => `/backoffice/groups/${groupId}/lock`,
    approveGroup: (groupId: string) => `/backoffice/groups/${groupId}/approve`,
    events: "/backoffice/events",
    pendingEvents: "/backoffice/events/pending",
    approveEvent: (eventId: string) => `/backoffice/events/${eventId}/approve`,
    pendingDealRooms: "/backoffice/dealrooms/pending",
    approveDealRoom: (roomId: string) => `/dealrooms/${roomId}/approve`,
    dealRoomLogs: "/backoffice/dealrooms/logs",
    dealRoomAuditLog: (roomId: string) => `/backoffice/dealrooms/${roomId}/audit-log`,
    lockDealRoom: (roomId: string) => `/backoffice/dealrooms/${roomId}/lock`,
    moderationPosts: "/backoffice/content/posts",
    moderationResources: "/backoffice/content/resources",
    moderationResourceById: (resourceId: string) =>
      `/backoffice/content/resources/${resourceId}`,
    archiveResource: (resourceId: string) =>
      `/backoffice/content/resources/${resourceId}/archive`,
    newsfeed: "/backoffice/newsfeed",
    newsfeedById: (postId: string) => `/backoffice/newsfeed/${postId}`,
  },
  events: {
    create: "/events",
    byId: (eventId: string) => `/events/${eventId}`,
  },
  newsfeed: {
    list: "/newsfeed",
    byId: (postId: string) => `/newsfeed/${postId}`,
  },
  dealrooms: {
    list: "/dealrooms",
    byId: (roomId: string) => `/dealrooms/${roomId}`,
    members: (roomId: string) => `/dealrooms/${roomId}/members`,
    memberById: (roomId: string, userId: string) =>
      `/dealrooms/${roomId}/members/${userId}`,
  },
  resources: {
    list: "/resources",
    download: (resourceId: string) => `/resources/download/${resourceId}`,
    userUploaded: "/backoffice/resources/user-uploaded",
    pending: "/backoffice/resources/pending",
    review: (resourceId: string) => `/resources/${resourceId}/review`,
    delete: (resourceId: string) => `/resources/${resourceId}`,
  },
  notifications: {
    sendEmail: "/notifications/send-email",
  },
  profile: {
    get: "/users/profile",
    setup: "/users/profile/setup",
    update: "/users/profile",
    avatar: "/users/profile/avatar",
    changePassword: "/users/profile/change-password",
    preferences: "/users/preferences",
  },
  security: {
    logs: "/backoffice/security-logs",
  },
} as const;
